/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  TransactionLog,
  TransactionLogInterface,
} from "../TransactionLog";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "employer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "worker",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "date",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum TransactionLog.Action",
        name: "action",
        type: "uint8",
      },
    ],
    name: "TransactionLogged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "employer",
        type: "address",
      },
      {
        internalType: "address",
        name: "worker",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "date",
        type: "uint256",
      },
      {
        internalType: "enum TransactionLog.Action",
        name: "action",
        type: "uint8",
      },
    ],
    name: "logTransaction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102c38061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806378b6b4cb14610030575b600080fd5b61004a60048036038101906100459190610177565b61004c565b005b8273ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff167fb249c4e993ab12127b3c769f0ab8b2cd475691ab9ee88bbca4906204c976900984846040516100ab929190610264565b60405180910390a350505050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100e9826100be565b9050919050565b6100f9816100de565b811461010457600080fd5b50565b600081359050610116816100f0565b92915050565b6000819050919050565b61012f8161011c565b811461013a57600080fd5b50565b60008135905061014c81610126565b92915050565b6005811061015f57600080fd5b50565b60008135905061017181610152565b92915050565b60008060008060808587031215610191576101906100b9565b5b600061019f87828801610107565b94505060206101b087828801610107565b93505060406101c18782880161013d565b92505060606101d287828801610162565b91505092959194509250565b6101e78161011c565b82525050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602160045260246000fd5b6005811061022d5761022c6101ed565b5b50565b600081905061023e8261021c565b919050565b600061024e82610230565b9050919050565b61025e81610243565b82525050565b600060408201905061027960008301856101de565b6102866020830184610255565b939250505056fea26469706673582212200265eacf06fe303182674f9bd3741d6b95b90a95f259e6475aa093d9ec7efac864736f6c634300081c0033";

type TransactionLogConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TransactionLogConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TransactionLog__factory extends ContractFactory {
  constructor(...args: TransactionLogConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TransactionLog & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TransactionLog__factory {
    return super.connect(runner) as TransactionLog__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TransactionLogInterface {
    return new Interface(_abi) as TransactionLogInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TransactionLog {
    return new Contract(address, _abi, runner) as unknown as TransactionLog;
  }
}
