// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using wdb_backend.Data;

#nullable disable

namespace wdb_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604001747_AddCertificationFields")]
    partial class AddCertificationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("wdb_backend.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("categories");
                });

            modelBuilder.Entity("wdb_backend.Models.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockchainAddress")
                        .HasColumnType("text")
                        .HasColumnName("blockchain_address");

                    b.Property<string>("CertificationFileName")
                        .HasColumnType("text")
                        .HasColumnName("certification_file_name");

                    b.Property<string>("CertificationFilePath")
                        .HasColumnType("text")
                        .HasColumnName("certification_file_path");

                    b.Property<string>("CertificationStatus")
                        .HasColumnType("text")
                        .HasColumnName("certification_status");

                    b.Property<int>("CertificationUploadedAt")
                        .HasColumnType("integer")
                        .HasColumnName("certification_uploaded_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("text")
                        .HasColumnName("private_key");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id");

                    b.ToTable("employer");
                });

            modelBuilder.Entity("wdb_backend.Models.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_type");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "FieldName")
                        .IsUnique();

                    b.HasIndex("CategoryId", "Label")
                        .IsUnique();

                    b.ToTable("fields");
                });

            modelBuilder.Entity("wdb_backend.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid?>("RecipientEmployerId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_employer_id");

                    b.Property<Guid?>("RecipientWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_worker_id");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RecipientEmployerId");

                    b.HasIndex("RecipientWorkerId");

                    b.HasIndex("RequestId");

                    b.ToTable("notification", t =>
                        {
                            t.HasCheckConstraint("CK_notification_single_recipient", "(recipient_worker_id IS NOT NULL) <> (recipient_employer_id IS NOT NULL)");

                            t.HasCheckConstraint("CK_notification_type", "type IN ('NEW_REQUEST', 'DATA_ACCESSED', 'REQUEST_REVIEWED', 'ACCESS_REVOKED')");
                        });
                });

            modelBuilder.Entity("wdb_backend.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<Guid?>("InfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("info_id");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("InfoId");

                    b.HasIndex("RequestId");

                    b.ToTable("permission", t =>
                        {
                            t.HasCheckConstraint("CK_permission_approved_has_info", "status NOT IN (1, 3) OR info_id IS NOT NULL");

                            t.HasCheckConstraint("CK_permission_field_or_info", "field_id IS NOT NULL OR info_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("wdb_backend.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomRequest")
                        .HasColumnType("text")
                        .HasColumnName("custom_request");

                    b.Property<string>("CustomRequestStatus")
                        .HasColumnType("text")
                        .HasColumnName("custom_request_status");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uuid")
                        .HasColumnName("employer_id");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("request");
                });

            modelBuilder.Entity("wdb_backend.Models.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockchainAddress")
                        .HasColumnType("text")
                        .HasColumnName("blockchain_address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("text")
                        .HasColumnName("private_key");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id");

                    b.ToTable("worker");
                });

            modelBuilder.Entity("wdb_backend.Models.WorkerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomLabel")
                        .HasColumnType("text")
                        .HasColumnName("custom_label");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("WorkerId", "CustomLabel")
                        .IsUnique()
                        .HasFilter("custom_label IS NOT NULL");

                    b.HasIndex("WorkerId", "FieldId")
                        .IsUnique()
                        .HasFilter("field_id IS NOT NULL");

                    b.ToTable("worker_info", t =>
                        {
                            t.HasCheckConstraint("CK_worker_info_field_xor_custom", "(field_id IS NOT NULL) <> (custom_label IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("wdb_backend.Models.Field", b =>
                {
                    b.HasOne("wdb_backend.Models.Category", "Category")
                        .WithMany("Fields")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("wdb_backend.Models.Notification", b =>
                {
                    b.HasOne("wdb_backend.Models.Employer", "RecipientEmployer")
                        .WithMany()
                        .HasForeignKey("RecipientEmployerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("wdb_backend.Models.Worker", "RecipientWorker")
                        .WithMany()
                        .HasForeignKey("RecipientWorkerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("wdb_backend.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecipientEmployer");

                    b.Navigation("RecipientWorker");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("wdb_backend.Models.Permission", b =>
                {
                    b.HasOne("wdb_backend.Models.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wdb_backend.Models.WorkerInfo", "WorkerInfo")
                        .WithMany("Permissions")
                        .HasForeignKey("InfoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wdb_backend.Models.Request", "Request")
                        .WithMany("Permissions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Request");

                    b.Navigation("WorkerInfo");
                });

            modelBuilder.Entity("wdb_backend.Models.Request", b =>
                {
                    b.HasOne("wdb_backend.Models.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wdb_backend.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("wdb_backend.Models.WorkerInfo", b =>
                {
                    b.HasOne("wdb_backend.Models.Field", "Field")
                        .WithMany("WorkerInfos")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wdb_backend.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("wdb_backend.Models.Category", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("wdb_backend.Models.Field", b =>
                {
                    b.Navigation("WorkerInfos");
                });

            modelBuilder.Entity("wdb_backend.Models.Request", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("wdb_backend.Models.WorkerInfo", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
