/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TransactionLogInterface extends Interface {
  getFunction(nameOrSignature: "logTransaction"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TransactionLogged"): EventFragment;

  encodeFunctionData(
    functionFragment: "logTransaction",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "logTransaction",
    data: BytesLike
  ): Result;
}

export namespace TransactionLoggedEvent {
  export type InputTuple = [
    employer: AddressLike,
    worker: AddressLike,
    date: BigNumberish,
    action: BigNumberish
  ];
  export type OutputTuple = [
    employer: string,
    worker: string,
    date: bigint,
    action: bigint
  ];
  export interface OutputObject {
    employer: string;
    worker: string;
    date: bigint;
    action: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TransactionLog extends BaseContract {
  connect(runner?: ContractRunner | null): TransactionLog;
  waitForDeployment(): Promise<this>;

  interface: TransactionLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  logTransaction: TypedContractMethod<
    [
      employer: AddressLike,
      worker: AddressLike,
      date: BigNumberish,
      action: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "logTransaction"
  ): TypedContractMethod<
    [
      employer: AddressLike,
      worker: AddressLike,
      date: BigNumberish,
      action: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TransactionLogged"
  ): TypedContractEvent<
    TransactionLoggedEvent.InputTuple,
    TransactionLoggedEvent.OutputTuple,
    TransactionLoggedEvent.OutputObject
  >;

  filters: {
    "TransactionLogged(address,address,uint256,uint8)": TypedContractEvent<
      TransactionLoggedEvent.InputTuple,
      TransactionLoggedEvent.OutputTuple,
      TransactionLoggedEvent.OutputObject
    >;
    TransactionLogged: TypedContractEvent<
      TransactionLoggedEvent.InputTuple,
      TransactionLoggedEvent.OutputTuple,
      TransactionLoggedEvent.OutputObject
    >;
  };
}
