using System.ComponentModel.DataAnnotations.Schema;
namespace wdb_backend.Models;

/// <summary>
/// Represents an employer in the system. Maps to the "worker" table in the database.
/// </summary>
[Table("employer")]
public class Employer
{
    /// <summary>
    /// Unique identifier (UUID), auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Worker's full name.
    /// </summary>
    [Column("name")]
    public required string Name { get; set; }

    /// <summary>
    /// Worker's email address.
    /// </summary>
    [Column("email")]
    public required string Email { get; set; }

    /// <summary>
    /// Timestamp of when the record was created. Auto-generated by the database.
    /// </summary>
    [Column("created_at")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Whether the worker's identity has been verified.
    /// </summary>
    [Column("verified")]
    public bool Verified { get; set; }

    /// <summary>
    /// Blockchain address derived from the public key.
    /// Used to identify this user on the blockchain.
    /// </summary>
    [Column("blockchain_address")]
    public string? BlockchainAddress { get; set; }

    /// <summary>
    /// Private key used to sign blockchain transactions.
    /// Stored here for simplicity during development.
    /// Move to Key Vault before going to production.
    /// </summary>
    [Column("private_key")]
    public string? PrivateKey { get; set; }


}
