using System.ComponentModel.DataAnnotations.Schema;
using wdb_backend.Abstractions;

namespace wdb_backend.Models;

/// <summary>
/// Represents an employer in the system. Maps to the "employer" table in the database.
/// </summary>
[Table("employer")]
public class Employer : IUser
{
    /// <summary>
    /// Unique identifier (UUID), auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Employer's company name.
    /// </summary>
    [Column("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Employer's email address.
    /// </summary>
    [Column("email")]
    public string Email { get; set; } = string.Empty;

    [Column("password")]
    public string Password { get; set; } = string.Empty;

    /// <summary>
    /// Timestamp of when the record was created. Auto-generated by the database.
    /// </summary>
    [Column("created_at")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Whether the employer's identity has been verified.
    /// </summary>
    [Column("verified")]
    public bool Verified { get; set; }

    /// <summary>
    /// Blockchain address derived from the public key.
    /// Used to identify this user on the blockchain.
    /// </summary>
    [Column("blockchain_address")]
    public string? BlockchainAddress { get; set; }

    /// <summary>
    /// Private key used to sign blockchain transactions.
    /// Stored here for simplicity during development.
    /// Move to Key Vault before going to production.
    /// </summary>
    [Column("private_key")]
    public string? PrivateKey { get; set; }


    [Column("certification_status")]
    public string? CertificationStatus { get; set; }


    [Column("certification_file_name")]
    public string? CertificationFileName { get; set; }

    [Column("certification_file_path")]
    public string? CertificationFilePath { get; set; }

    [Column("certification_uploaded_at")]
    public DateTime? CertificationUploadedAt { get; set; }
}
