using System.ComponentModel.DataAnnotations.Schema;

namespace wdb_backend.Models;

/// <summary>
/// Represents a data-access request submitted by an employer for a specific worker.
/// Maps to the "request" table in the database.
/// </summary>
[Table("request")]
public class Request
{
    /// <summary>
    /// Unique identifier, auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Foreign key referencing the employer who submitted the request.
    /// </summary>
    [Column("employer_id")]
    public Guid EmployerId { get; set; }

    /// <summary>
    /// Foreign key referencing the worker whose data is being requested.
    /// </summary>
    [Column("worker_id")]
    public Guid WorkerId { get; set; }

    /// <summary>
    /// The reason the employer provides for needing access to the worker's data.
    /// </summary>
    [Column("reason")]
    public required string Reason { get; set; }

    /// <summary>
    /// The date and time at which all approved permissions under this request expire.
    /// This is set by the worker during review, not by the employer.
    /// It is null while the request is pending or fully rejected.
    /// </summary>
    [Column("expiry_date")]
    public DateTime? ExpiryDate { get; set; }

    /// <summary>
    /// Free-text description of additional data the employer needs that the worker
    /// does not yet have as a preset or existing custom field.
    /// Null if the employer did not include a custom request.
    /// </summary>
    [Column("custom_request")]
    public string? CustomRequest { get; set; }

    /// <summary>
    /// Processing status of the custom_request field:
    ///   null     no custom request was made
    ///   pending  worker has not yet responded
    ///   approved worker created the item via Add Item
    ///   rejected worker declined the custom request
    /// </summary>
    [Column("custom_request_status")]
    public string? CustomRequestStatus { get; set; }

    /// <summary>
    /// Timestamp of when the record was created. Set by the database.
    /// </summary>
    [Column("created_at")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedAt { get; set; }

    // Navigation
    public Employer Employer { get; set; } = null!;
    public Worker Worker { get; set; } = null!;
    public ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}
