using System.ComponentModel.DataAnnotations.Schema;
namespace wdb_backend.Models;

/// <summary>
/// Represents a worker's information in the system. Maps to the "worker_info" table in the database.
/// </summary>
[Table("worker_info")]
public class WorkerInfo
{
    /// <summary>
    /// Unique identifier (UUID), auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Foreign key referencing the worker who owns this information..
    /// </summary>
    [Column("worker_id")]
    public Guid WorkerId { get; set; }

    /// <summary>
    /// Timestamp of when the record was created. Auto-generated by the database.
    /// </summary>
    [Column("created_at")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedAt { get; set; }

    
    /// <summary>
    /// The information title such as gender, address. 
    /// </summary>
    [Column("desc")]    
     public required string Desc { get; set; }

    /// <summary>
    /// The value of the information. 
    /// </summary>
    [Column("value")]    
     public required string Value { get; set; }

}
    
