using System.ComponentModel.DataAnnotations.Schema;
namespace wdb_backend.Models;

/// <summary>
/// Represents a worker in the system. Maps to the "worker" table in the database.
/// </summary>
[Table("worker")]
public class Worker
{
    /// <summary>
    /// Unique identifier (UUID), auto-generated by the database.
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// Worker's full name.
    /// </summary>
    [Column("name")]
    public string Name { get; set; }

    /// <summary>
    /// Worker's email address.
    /// </summary>
    [Column("email")]
    public string Email { get; set; }

    /// <summary>
    /// Timestamp of when the record was created. Auto-generated by the database.
    /// </summary>
    [Column("created_at")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedAt { get; set; }

}
